### ISSUE TITLE
Make npm package public

### ISSUE THREAD

**Issue by RyanZim** [ExodusMovement/xpub-converter#2]
Given that this is a public repo, based on publicly-available open-source code, there's no reason for the npm package to be private. The one open question is whether a public package should be scoped to the organization; or just published in the global scope. `xpub-converter` is available in the global scope; and this package would be generally useful to the ecosystem; I would lean strongly towards making it unscoped. Any objection?

**Comment by gutenye** [comment]
Let's do it. Is there a way to make `@exodus/xpub-converter` public while still use the `exodus` scope? If so, I think scoped to the organization is the best option. If not, can we create a new scope dedicated to the public packages?

**Comment by RyanZim** [comment]
We can make it public while keeping the `@exodus` scope. 

> I think scoped to the organization is the best option.

Why? Just curious.

**Comment by gutenye** [comment]
It clearly shows that the package is forked by Exodus. Otherwise, in the global scope, which name would like to pick? `xpub-converter2`? or `exodus-xpub-converter`? (this basically is the same as `@exodus/xpub-converter`)

**Comment by RyanZim** [comment]
@gutenye There is no npm package named `xpub-converter`; https://github.com/jlopp/xpub-converter from which this is adapted (not directly forked), is a browser tool that doesn't have an API and isn't on npm.

**Comment by gutenye** [comment]
Oh, okay, I'm fine with either way. @RyanZim I'll leave for you to decide.
